name: 'build-editor'
on:
  workflow_dispatch:
    inputs:
      engine:
        description: "Continue publishing the editor?"
        required: true
        default: 'yes'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: ⚙ Update submodules
        run: git submodule update --init --recursive --remote

      - name: ⚙ Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1

      - name: ⚙ Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install

      - name: 🛠 Compile the editor only
        env:
          SF_COMPILER_IDLE_TERMINATE_TIME: 10 # seconds
          EDITOR_ONLY: true
        run: npm run compile

      - name: ⚙ Delete some files
        run: rm -rf editor/src && rm -rf editor/docs && rm -rf editor/utils

      - name: 🚀 Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          folder: editor
          repository-name: Blackprint/blackprint.github.io
          branch: gh-pages
          single-commit: true